apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-test
  labels:
    app: docker-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker-test
  template:
    metadata:
      labels:
        app: docker-test
    spec:
      containers:
        - name: my-app
          image: criptoempi/app:1.0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: docker-test-service
spec:
  selector:
    app: docker-test
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
