apiVersion: v1
kind: Pod
metadata:
  name: pibic
  labels:
    env: test
spec:
  containers:
    - name: pibic
      image: criptoempi/pibic:1.0
      imagePullPolicy: IfNotPresent
  nodeSelector:
    disktype: ssd
